src/components/Header/Header.jsx, src/components/Header/Header.style.jsx, src/components/Header/index.js, src/components/index.js, src/pages/AddCardPage/AddCardPage.jsx, src/pages/HomePage/HomePage.jsx, src/pages/HomePage/HomePage.style.jsx, src/pages/MyPage/MyPage.jsx, src/pages/MyPage/MyPage.style.jsx, src/pages/OnBoardingPage/OnBoardingPage.jsx, src/pages/OnBoardingPage/OnBoardingPage.style.jsx, src/pages/ViewCardPage/ViewCardPage.jsx, src/router.jsx
=> feat: 헤더 컴포넌트 생성

src/components/SearchBar/SearchBar.jsx, src/components/SearchBar/SearchBar.style.jsx, src/components/SearchBar/index.js, src/components/index.js, src/pages/AddCardPage/AddCardPage.jsx, src/pages/AddCardPage/AddCardPage.style.jsx, src/pages/ViewCardPage/ViewCardPage.jsx, src/pages/ViewCardPage/ViewCardPage.style.jsx
=> feat: 검색창 컴포넌트 생성 및 적용

src/components/Button/BlueButton.jsx, src/components/Button/BlueButton.style.jsx, src/components/Button/PrimaryButton.jsx, src/components/Button/PrimaryButton.style.jsx, src/components/Button/SecondaryButton.jsx, src/components/Button/SecondaryButton.style.jsx, src/components/Button/index.js, src/components/index.js, src/pages/AddCardPage/AddCardPage.jsx, src/pages/AddCardPage/AddCardPage.style.jsx, src/pages/ViewCardPage/ViewCardPage.jsx, src/styles/welletStyles.style.js
- BlueButton: 그룹(전체보기, 비즈니스 등)/ 명함 추가(이미지로, 직접 입력) 등
- PrimaryButton : 시작하기, 로그인, 등록 등
- SecondaryButton: 건너뛰기, 취소 등
- BlueButton
- PrimaryButton, SecondaryButton
- 모두 적용
=> feat: 버튼 컴포넌트 구현

index.html, src/pages/MyPage/MyPage.jsx, src/pages/MyPage/MyPage.style.jsx, src/styles/welletStyles.style.js
- 마이페이지 내 컴포넌트 너비 설정 해제
- 마이페이지 내 하단 탭바 추가 및 코드 포맷팅
- min-width: 360px -> 320px으로 수정
- initial-scale: 1.5 -> 1.0으로 수정
=> Modify: initial-scale 값 및 CSS 속성 일부 수정

src/pages/MyPage/MyPage.jsx, src/pages/MyPageEdit/MyPageEdit.jsx, src/pages/MyPageEdit/MyPageEdit.style.jsx, src/pages/MyPageEdit/index.js, src/pages/index.js, src/router.jsx
-mypage 편집경로 설정, mypage-edit 파일 생성
=> Feat:mypage 편집경로 설정, mypage-edit 파일 생성

index.html
- 메타태그 작성
<br />
```javascript
<meta property="og:url" content="https://wellet.netlify.app/" />
<meta property="og:title" content="WELLET" />
<meta property="og:type" content="website" />
<meta property="og:image" content="https://src/assets/images/favicon-wellet.png" />
<meta property="og:description" content="WELLET | 우리(WE)들이 사용하는 월렛" />
```
=> Feat: 메타태그 작성

src/pages/AddCardPage/AddCardPage.jsx
- 명함 추가 페이지 내 프로필 사진 등록 기능 구현
<br />
=> Feat: 명함 추가 페이지 내 프로필 사진 등록 기능 구현

src/pages/AddCardPage/AddCardPage.jsx, src/pages/AddCardPage/AddCardPage.style.jsx
- 명함 추가 페이지 내 drag & drop 기능 및 스타일 적용
<br />
https://github.com/user-attachments/assets/89e2b48e-c28c-41f2-a734-0ad4dc186ad6
=> Feat: 명함 추가 페이지 내 drag & drop 기능 구현

src/pages/AddCardPage/AddCardPage.jsx
- 명함 추가 페이지 내 직접 입력 항목 리팩토링
<br />
=> Refactor: 명함 추가 페이지 내 직접 입력 항목 리팩토링

src/icons/icon-arrow-down.svg, src/icons/icon-arrow.svg, src/icons/icon-pencil2.svg, src/icons/icon-x.svg, src/pages/MyPage/MyPage.jsx, src/pages/MyPage/MyPage.style.jsx
=> Feat: mypage 수정

src/assets/icon.svg, src/pages/MyPageEdit/MyPageEdit.jsx, src/pages/MyPageEdit/MyPageEdit.style.jsx, src/pages/MyPageEditPage/MyPageEditPage.jsx, src/pages/MyPageEditPage/MyPageEditPage.style.jsx, src/pages/MyPageEditPage/index.js, src/pages/index.js, src/router.jsx
-마이페이지 편집 기능 구현하였습니다. (프로필 사진 제외)
-이름 수정 시 필드가 나오는 것은 수정 예정입니다.
-수정 시 편리함을 위해 직책, 부서 분리하였습니다.
<br />
=> Fix: 마이페이지편집 뷰, 기능 구현

src/pages/MyPage/MyPage.jsx, src/pages/MyPage/MyPage.style.jsx, src/router.jsx
-마이페이지 css 수정하였습니다.
-컴포넌트 이름, css 수정
-아이콘 적용
<br />
=> Fix: 마이페이지 css 수정

src/components/Layout/Layout.jsx, src/components/Layout/index.js, src/components/index.js, src/main.jsx, src/pages/AddCardPage/AddCardPage.jsx, src/pages/CardDetailPage/CardDetailPage.jsx, src/pages/DetailEditPage/DetailEditPage.jsx, src/pages/HomePage/HomePage.jsx, src/pages/HomePage/HomePage.style.jsx, src/pages/MyPage/MyPage.jsx, src/pages/MyPageEditPage/MyPageEditPage.jsx, src/pages/ViewCardPage/ViewCardPage.jsx, src/router.jsx, src/utils/HomePageUtils/homePageUtils.js
- 탭바 깜박임 오류 해결
- 홈 페이지의 필터 옵션, 그룹 수정 버튼 삭제
- 필터 옵션, 그룹 삭제하면서 생긴 여백만큼 HomepageUtils의 높이 계산 함수 내부 값 수정
<br />
- 렌더링을 최소화 하는 코드로 리팩토링하긴 했지만, 실제로 잘 작동하는지는 main으로 내려 배포버전에서 확인할 수 있을 듯함.
- TabBar 수정하면서 (브랜치 새로 파기 귀찮아서^^) 겸사겸사 필터 옵션, 그룹 수정 버튼 삭제도 같이 했습니다 :) 
<br />
=> Fix: 탭바 깜박임 오류 해결 & 불필요한 버튼 제거

index.html, src/components/TabBar/TabBar.style.jsx
- 아이폰 safe-area 처리 테스트(1)
- : 아이폰 환경이면 TabBar 아래 padding 붙이도록 설정
<br />
- FE 회의 때 테스트 해보고 오류 있을 시 수정 예정
<br />
=> Test: 아이폰 safe-area 처리 테스트(1)

src/assets/icons/icon.svg, src/pages/DetailEditPage/DetailEditPage.jsx
- 프로필이미지 편집 안되는 오류 해결 (최신 배포 후 오류 발견)
- 왼쪽 화살표 아이콘 stroke값 추가
<br />
<br />
<br />
- 뱃지 컴포넌트 구현 중
<br />
=> Fix: 프로필이미지 편집 오류 해결

src/components/BadgeDetail/BadgeDetail.jsx, src/components/BadgeDetail/BadgeDetail.style.jsx, src/components/BadgeDetail/index.js, src/components/index.js, src/pages/CardDetailPage/CardDetailPage.jsx, src/pages/DetailEditPage/DetailEditPage.jsx
- 상세 페이지 내 그룹뱃지 별도 구현
- 다른 사람 명함 편집페이지에서 그룹뱃지 클릭하고 편집완료 누르면 데이터 저장되도록 코드 수정
<br />
<br />
<br />
- 이미지 보기 구현 예정
<br />
=> Feat: 그룹뱃지 컴포넌트 구현 및 수정

.github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/refactor-template.md
- 이슈 템플릿 내 타이틀 추가
<br />
<br />
=> #83 [DOCS] 이슈 템플릿 내 타이틀 추가

.github/ISSUE_TEMPLATE/feature-request.md, README.md
=> #83 [DOCS] README.md 수정

src/pages/DetailEditPage/DetailEditPage.jsx, src/pages/DetailEditPage/DetailEditPage.style.jsx
- 남의 명함 사진 수정 구현
<br />
<br />
|수정 전|수정 후|
|----|----|
|<img width="250" alt="" src="https://github.com/user-attachments/assets/939f1df7-7422-4fd7-acfc-f471147bf500">|<img width="250" alt="" src="https://github.com/user-attachments/assets/532d6d94-dffa-45a4-a6aa-913cbcb5acb8"> |
<br />
=> #98 [FEAT] 남 명함 사진 수정 구현

src/apis/cards.js, src/apis/group.js, src/apis/myCard.js, src/pages/HomePage/HomePage.jsx
- API member_id 대신 token 쓰는 방식으로 변경
=> #113 [REFACTOR] API member_id 대신 token 쓰는 방식으로 변경

src/apis/cards.js, src/axios/index.js, src/components/SearchBar/SearchBar.jsx, src/pages/HomePage/HomePage.jsx, src/pages/HomePage/HomePage.style.jsx
- 검색 API 연결 (데이터 받아오기까지)
- 홈 화면에서 키워드 넣고 검색 시 명함보기 페이지로 이동
- 검색 키워드 유지
- 홈 화면에 내 명함 데이터 없으면 문구 띄우기
<br />
https://github.com/user-attachments/assets/2d8dde4f-c218-4e62-981b-e1430a6a409b
<br />
=> #110 [FEAT] 명함 검색 API 연결 

src/components/AddGroupModal/AddGroupModal.jsx, src/pages/DetailEditPage/DetailEditPage.jsx, src/pages/HomePage/HomePage.jsx
- 그룹 API 토큰 방식으로 수정
<br />
<br />
=> #116 [FEAT] 그룹 API 토큰 방식으로 수정

src/apis/cards.js, src/apis/index.js, src/axios/index.js, src/components/CardInfo/CardInfo.jsx, src/hooks/useFormData.js, src/pages/CardDetailPage/CardDetailPage.jsx, src/pages/DetailEditPage/DetailEditPage.jsx, src/pages/DetailEditPage/DetailEditPage.style.jsx, src/pages/HomePage/HomePage.jsx, src/pages/ViewCardPage/ViewCardPage.jsx
- Axios Header Content-Type 기본값 "multipart/form-data"로 설정
- json 타입 form-data로 바꾸는 useFormData 훅 추가함
- 명함 보기 페이지에서 명함 조회, 상세 조회, 수정 API 연결
- job은 position, team은 department로 속성 수정
<br />
<br />
=> #118 [FEAT] 명함 보기 페이지에서 명함 조회, 상세 조회, 수정 API 연결

src/apis/login.js, src/axios/index.js, src/pages/LoginPage/LoginPage.jsx
=> #122 [FEAT] 로그인 수정

src/apis/index.js, src/pages/LoginPage/LoginPage.jsx
=> #122 [FEAT] 로그인코드 수정

vite.config.js
=> #129 [FIX] 로그인 오류: 포트번호 8000번으로 수정

src/pages/HomePage/HomePage.jsx
- 홈페이지 내 명함 위치 수정
<br />
<br />
<br />
=> #131 [FIX] 홈페이지 내 명함 위치 수정

src/apis/login.js
- [긴급] 로그인 오류 해결 시도: 서버 도메인 환경변수 처리
<br />
=> #134 [FIX] 서버 도메인 수정(2)

src/apis/login.js, src/axios/index.js, src/pages/LoginPage/LoginPage.jsx
- #138 
- 기존에 사용하던 dummy 대신 실제 cookie값을 받아와 헤더에 토큰값 넣도록 로직 수정
<br />
- 배포 환경에서 테스트할 예정입니다.
- 쿠키가 잘 받아지는지 확인하기 위해 콘솔 코드를 몇 개 추가했습니다.
<br />
=> #138 [FIX] 쿠키에서 jwt토큰 받기

src/apis/cards.js, src/axios/index.js
=> #141 [FIX] 프론트 쿠키 접근 로직 제거

src/pages/LoginPage/LoginPage.jsx
- 프론트 쿠키 접근 로직 제거 작업 바로 main에 반영해서 테스트할 예정
=> [DEPLOY] dev to main 

src/pages/AddCardPage/AddCardPage.jsx, src/pages/AddCardPage/DirectInputForm.jsx, src/pages/ViewCardPage/ViewCardPage.jsx
- 명함 직접 추가 및 해당 페이지 내 그룹명 조회 API 연동
<br />
<br />
=> #115 [FEAT] 명함 직접 추가 및 해당 페이지 내 그룹명 조회 API 연동

src/pages/AddCardPage/AddCardPage.jsx
- 명함등록 페이지 쿼리 스트링 구현
<br />
<br />
<br />
=> #155 [FEAT] 명함등록 페이지 쿼리 스트링 구현

src/components/CardInfo/CardInfo.jsx
- `직책`과 `부서`가 모두 있는 경우에만 슬래시(`/`) 삽입
<br />
<br />
<br />
=> #156 [FEAT] `직책`과 `부서`가 모두 있는 경우에만 슬래시(`/`) 삽입

src/components/AddGroupModal/AddGroupModal.jsx, src/components/MyCard/MyCard.jsx, src/components/MyCard/MyCard.style.jsx, src/pages/DetailEditPage/DetailEditPage.jsx, src/pages/HomePage/HomePage.jsx
close #159 
- 홈 페이지 내 명함
- Address 입력 안 하면 아예 Address가 안 뜨도록
- TEL 대신 PHONE 데이터 띄우기
- 회사 | 부서 | 직책 띄우기
- 받아온 프로필 이미지 띄우기
- 홈 페이지 둘러보기
- 스크롤 생기지 않는 최대 개수 보여주도록
- 명함보기 페이지
- 그룹 삭제에 뜨던 오류 해결 
- 생성한 그룹 명함 편집 페이지에 바로 반영 
<br />
<br />
=> #159 [FIX] 홈 화면, 그룹 관련 퍼블리싱 오류 해결 

src/pages/HomePage/HomePage.jsx, src/utils/HomePageUtils/homePageUtils.js
=> #159 [STYLE] 홈 화면 둘러보기에 스크롤 없도록 최대 명함 개수 계산 로직 추가

src/apis/cards.js, src/apis/index.js, src/pages/ViewCardPage/ViewCardPage.jsx
- 명함 동시 삭제 api 연결
<br />
https://github.com/user-attachments/assets/e1dda99a-9dce-4ba0-8797-783446c8c09f
=> #157 [FEAT] 명함 동시 삭제 api 연결

src/apis/index.js, src/apis/myCard.js, src/pages/MyPageEditPage/MyPageEditPage.jsx
- 내 명함 프로필이미지 api 수정 반영
- 내 명함 아이콘 제거
<br />
<br />
<br />
=> #99 [FEAT] 내 명함 프로필이미지 api 수정 반영 및 아이콘 제거

src/pages/AddCardPage/AddCardPage.style.jsx, src/pages/AddCardPage/DirectInputForm.jsx, src/pages/AddCardPage/inputFields.js
- 이메일 필수값 제거, 그룹 필수값 추가
<br />
<br />
=> #174 [MODIFY] 이메일 필수값 제거, 그룹 필수값 추가

src/axios/index.js, src/main.jsx
- 토큰 만료시 '/login'으로 navigate하도록 axios intercepter 설정
<br />
=> #173 [FEAT] 토큰 만료시 '/login'으로 navigate

src/components/AddGroupModal/AddGroupModal.style.jsx, src/components/Badge/BlueBadge.style.jsx, src/components/Button/PrimaryButton.style.jsx, src/components/Button/SecondaryButton.style.jsx, src/components/CardInfo/CardInfo.style.jsx, src/components/InputWrapper/InputWrapper.style.jsx, src/components/MyCard/MyCard.style.jsx, src/components/OnboardingContent/OnboardingContent.style.jsx, src/components/SearchBar/SearchBar.jsx, src/components/SearchBar/SearchBar.style.jsx, src/components/TabBar/TabBar.style.jsx, src/pages/AddCardPage/AddCardPage.jsx, src/pages/AddCardPage/AddCardPage.style.jsx, src/pages/CardDetailPage/CardDetailPage.jsx, src/pages/CardDetailPage/CardDetailPage.style.jsx, src/pages/DetailEditPage/DetailEditPage.style.jsx, src/pages/HomePage/HomePage.style.jsx, src/pages/MyPage/MyPage.style.jsx, src/pages/ViewCardPage/ViewCardPage.style.jsx
- 기본 폰트사이즈 11px >> 14px로 수정
<br />
<br />
=> #183 [DESIGN] 기본 폰트사이즈 11px >> 14px로 수정

src/pages/AddCardPage/AddCardPage.jsx
- 휴대폰 번호 정규화 적용
- `+82`를 입력받는 경우
- `.`, `(빈칸)` 등과 같이, 숫자 이 외의 것이 입력되면 `-`으로 자동 변환
- 직접 입력을 통해 값을 입력할 경우에도 자동으로 `-` 입력  
<br />
<br />
<br />
=> #183 [FEAT] 휴대폰 번호 정규화 적용

src/pages/AddCardPage/AddCardPage.jsx, src/pages/AddCardPage/ImageInputForm.jsx
- 이미지 드래그 앤 드롭 기능 구현 (덮어쓰기 가능)
<br />
<br />
<br />
=> #182 [FIX] 이미지 드래그 앤 드롭 기능 구현

src/components/Header/Header.jsx, src/components/ImageUploadOverlay/ImageUploadOverlay.jsx, src/components/ImageUploadOverlay/ImageUploadOverlay.style.jsx, src/components/ImageUploadOverlay/index.js, src/components/InputWrapper/InputWrapper.jsx, src/components/index.js, src/pages/AddCardPage/AddCardPage.jsx, src/pages/AddCardPage/ImageInputForm.jsx
- OCR 로딩 효과 구현 ocr loading
- `ImageUploadOverlay` 컴포넌트 구현
- `이미지 등록` >> `등록중...` 문구변경
<br />
<br />
<br />
=> #186 [FEAT] OCR 로딩 효과 구현 ocr loading 효과 구현

src/apis/index.js, src/pages/AddCardPage/AddCardPage.jsx, src/pages/AddCardPage/AddCardPage.style.jsx, src/pages/AddCardPage/DirectInputForm.jsx
- 명함 추가 페이지에서 그룹 편집 모달 기능 구현
<br />
<br />
<br />
=> #185 [FEAT] 명함 추가 페이지에서 그룹 편집 모달 기능 구현

src/pages/AddCardPage/ImageInputForm.jsx
- 첨부한 명함 이미지 있을 경우에도, 이미지 수정을 위해 버튼 유지
<br />
<br />
<br />
=> #194 [FIX] 첨부한 명함 이미지 있을 경우에도, 이미지 수정을 위해 버튼 유지

src/pages/AddCardPage/ImageInputForm.jsx
- 이미지 1MB 이상의 파일도 업로드 가능하도록 수정
<br />
<br />
=> #197 [FIX] 이미지 1MB 이상의 파일도 업로드 가능하도록 수정

src/pages/AddCardPage/ImageInputForm.jsx
- 이미지 추가 영역을 선택해도 이미지 추가가 되도록 수정
<br />
<br />
=> #184 [FIX] 이미지 추가 영역을 선택해도 이미지 추가가 되도록 수정

src/pages/CardDetailPage/CardDetailPage.style.jsx, src/pages/MyPage/MyPage.style.jsx
- 폰트크기 변화에 따른 상세보기 언더바 위치 재조정 
<br />
<br />
<br />
=> #190 [FIX] 상세보기 언더바 위치 재조정

src/pages/CardDetailPage/CardDetailPage.jsx, src/pages/CardDetailPage/CardDetailPage.style.jsx, src/pages/DetailEditPage/DetailEditPage.jsx, src/pages/DetailEditPage/DetailEditPage.style.jsx
- 명함 이미지 추가 및 수정
- css 수정
- 현재 프로필이미지 프론트&백 이미지 동시 수정 불가 (하나를 수정하면 다른 것이 null됨)
<br />
<br />
<br />
=> #176 [FEAT] 명함 이미지 추가 및 수정 기능

src/pages/AddCardPage/AddCardPage.style.jsx
- 그룹 목록에 `flex-wrap: wrap` 속성 적용
<br />
<br />
<br />
=> #205 [FIX] 그룹 목록에 `flex-wrap: wrap` 속성 적용

src/pages/AddCardPage/AddCardPage.jsx
- 명함 추가 페이지 내 검색창 삭제
<br />
<br />
=> #206 [REMOVE] 명함 추가 페이지 내 검색창 삭제

src/pages/MyPage/MyPage.style.jsx, src/pages/MyPageEditPage/MyPageEditPage.style.jsx, src/pages/ViewCardPage/ViewCardPage.jsx
- 폰트 사이즈 및 문구 변경
<br />
<br />
=> #209 [DESIGN] 폰트 사이즈 및 문구 변경

src/pages/DetailEditPage/DetailEditPage.style.jsx, src/pages/MyPageEditPage/MyPageEditPage.style.jsx
- 편집할 항목들 폰트 색상 진하게
<br />
<br />
<br />
=> #204 [FIX] 명함 내 편집할 항목들 폰트 수정

src/pages/CardDetailPage/CardDetailPage.jsx
- 속한 그룹이 없을 때 조건 처리
<br />
<br />
<br />
=> #212 [FEAT] 속한 그룹이 없을 때 조건 처리

src/pages/CardDetailPage/CardDetailPage.jsx
- 아이콘에 전화/문자/메일 액션 연결
<br />
<br />
=> #213 [FEAT] 아이콘에 전화/문자/메일 액션 연결

src/components/Header/Header.jsx, src/components/MyCard/MyCard.jsx, src/pages/AddCardPage/AddCardPage.jsx, src/pages/DetailEditPage/DetailEditPage.jsx, src/pages/DetailEditPage/DetailEditPage.style.jsx, src/pages/HomePage/HomePage.jsx, src/pages/MyPage/MyPage.jsx, src/pages/MyPageEditPage/MyPageEditPage.jsx, src/utils/HomePageUtils/formatPhoneNumber.js
- MyCard에 null값 안 뜨도록
- MyCard에도 전화번호 format하도록 기존 formatPhoneNumber util로 분리하고 가져와서 사용
- 명함 편집에서 그룹 편집 주석 처리
- 헤더 로고에 width, height 명시적으로 주기
<br />
=> #217 [FIX] 자잘한 퍼블리싱 오류 해결

src/pages/ViewCardPage/ViewCardPage.jsx
- 아이콘에 width, height 명시적으로 줘서 쓰레기통 아이콘 안 뜨는 오류 해결
=> #220 [FIX] 쓰레기통 아이콘 안 뜨는 오류 해결

src/apis/cards.js, src/apis/group.js, src/apis/myCard.js, src/apis/ocr.js, src/components/AddGroupModal/AddGroupModal.jsx, src/components/Badge/BlueBadge.jsx, src/components/CardInfo/CardInfo.jsx, src/components/MyCard/MyCard.style.jsx, src/nextDevelopItems/EmailLoginPage/EmailLoginPage.jsx, src/pages/AddCardPage/AddCardPage.jsx, src/pages/AddCardPage/DirectInputForm.jsx, src/pages/DetailEditPage/DetailEditPage.jsx, src/pages/MyPage/MyPage.jsx, src/pages/MyPage/MyPage.style.jsx, src/pages/MyPageEditPage/MyPageEditPage.jsx, src/pages/ViewCardPage/ViewCardPage.jsx
- 자잘한 퍼블리싱 오류들 수정
- 사용하지 않는 스타일 삭제
- MyPage 폰트 16px로 통일
- MyCard ExtraInfo 12px로 키우기
- 모바일에서 안 뜨는 아이콘 width, height 명시적으로 주기
- 파일 전체 콘솔 로그 삭제
<br />
=> #223 [FIX] 퍼블리싱 오류 수정

src/pages/CardDetailPage/CardDetailPage.jsx, src/pages/CardDetailPage/CardDetailPage.style.jsx, src/pages/DetailEditPage/DetailEditPage.jsx, src/pages/LoginPage/LoginPage.jsx, src/pages/MyPage/MyPage.style.jsx, src/pages/MyPageEditPage/MyPageEditPage.jsx
- 폰트 사이즈, 간격 및 여백 수정 
- 카카오톡 아이콘, 연필 아이콘에 width, height값 명시적으로 부여 (모바일에서 안 뜨는 오류 해결)
<br />
=> #226 [FIX] 퍼블리싱 오류 수정

src/components/MyCard/MyCard.jsx, src/pages/HomePage/HomePage.jsx, src/pages/ViewCardPage/ViewCardPage.jsx
- 명함 최신 추가 순으로 정렬 (id 역순)
<br />
<br />
=> #234 [FEAT] 명함 최신 추가 순으로 정렬

src/pages/DetailEditPage/DetailEditPage.jsx
- 프로필이미지, 프론트백이미지 수정 구분하는 조건 추가
<br />
<br />
<br />
=> #239 [FIX] 사진 수정 alert창 조건 수정

src/pages/DetailEditPage/DetailEditPage.jsx
- 사진 수정 alert창 조건 추가 수정
- 문구 더 명확하게 변경
<br />
<br />
<br />
=> #239 [FIX] 사진 수정 alert창 조건 수정(2)

src/pages/DetailEditPage/DetailEditPage.jsx
=> dev to main
